// <auto-generated />
using System;
using BookwormApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookwormApi.Migrations
{
    [DbContext(typeof(BookwormDbContext))]
    partial class BookwormDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookwormApi.Models.AttributeEntity", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Attribute_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<string>("AttributeDesc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Attribute_Desc");

                    b.HasKey("AttributeId");

                    b.ToTable("attribute", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Author_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Bio")
                        .HasColumnType("longtext")
                        .HasColumnName("Bio");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("AuthorId");

                    b.ToTable("author", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("beneficiary_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("BeneficiaryAccNo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("beneficiary_acc_no");

                    b.Property<string>("BeneficiaryAccType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("beneficiary_acc_type");

                    b.Property<string>("BeneficiaryBankBranch")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("beneficiary_bank_branch");

                    b.Property<string>("BeneficiaryBankName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("beneficiary_bank_name");

                    b.Property<string>("BeneficiaryContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("beneficiary_contact_no");

                    b.Property<string>("BeneficiaryEmailId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("beneficiary_email_id");

                    b.Property<string>("BeneficiaryIfsc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("beneficiary_ifsc");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("beneficiary_name");

                    b.Property<string>("BeneficiaryPan")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("beneficiary_pan");

                    b.Property<string>("BeneficiaryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Other")
                        .HasColumnName("beneficiary_type");

                    b.HasKey("BeneficiaryId");

                    b.ToTable("beneficiary", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.BeneficiaryAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int")
                        .HasColumnName("beneficiary_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("ProductId", "BeneficiaryId")
                        .IsUnique();

                    b.ToTable("beneficiary_assignment", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<int?>("RentDays")
                        .HasColumnType("int")
                        .HasColumnName("rent_days");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Genere", b =>
                {
                    b.Property<int>("GenereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Genere_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GenereId"));

                    b.Property<string>("GenereDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Genere_Desc");

                    b.HasKey("GenereId");

                    b.HasIndex("GenereDesc")
                        .IsUnique();

                    b.ToTable("genere", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Language_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("LanguageDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Language_Desc");

                    b.HasKey("LanguageId");

                    b.HasIndex("LanguageDesc")
                        .IsUnique();

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.LibraryPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int>("BookLimit")
                        .HasColumnType("int")
                        .HasColumnName("book_limit");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int")
                        .HasColumnName("validity_days");

                    b.HasKey("PackageId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("library_package", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.LibraryPackagePurchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("AllowedBooks")
                        .HasColumnType("int")
                        .HasColumnName("allowed_books");

                    b.Property<decimal>("AvgBookPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("avg_book_price");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<decimal>("PackagePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("package_price");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchase_date");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PurchaseId");

                    b.HasIndex("PackageId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("library_package_purchase", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.LibraryPackagePurchaseItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("RoyaltyAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("royalty_amount");

                    b.Property<decimal>("RoyaltyPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("royalty_percent");

                    b.HasKey("ItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("library_package_purchase_item", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.MyLibrary", b =>
                {
                    b.Property<int>("MyLibId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("my_lib_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MyLibId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("access_type");

                    b.Property<int?>("BooksAllowed")
                        .HasColumnType("int")
                        .HasColumnName("books_allowed");

                    b.Property<int?>("BooksTaken")
                        .HasColumnType("int")
                        .HasColumnName("books_taken");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MyLibId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("my_library", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.MyShelf", b =>
                {
                    b.Property<int>("ShelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shelf_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShelfId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ShelfId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("my_shelf", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("product_author");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<int?>("GenereId")
                        .HasColumnType("int")
                        .HasColumnName("product_genere");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("product_lang");

                    b.Property<bool>("Library")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_library");

                    b.Property<int>("MinRentDays")
                        .HasColumnType("int")
                        .HasColumnName("min_rent_days");

                    b.Property<decimal>("ProductBaseprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("product_baseprice");

                    b.Property<string>("ProductDescriptionLong")
                        .HasColumnType("longtext")
                        .HasColumnName("product_description_long");

                    b.Property<string>("ProductDescriptionShort")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_description_short");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_Image");

                    b.Property<string>("ProductIsbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("product_isbn");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductNameEnglish")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("product_name_english");

                    b.Property<DateOnly?>("ProductOffPriceExpirydate")
                        .HasColumnType("date")
                        .HasColumnName("product_off_price_expirydate");

                    b.Property<decimal?>("ProductOfferprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("product_offerprice");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("product_publisher");

                    b.Property<decimal?>("RentPerDay")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("rent_per_day");

                    b.Property<bool>("Rentable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_rentable");

                    b.Property<decimal?>("RoyaltyPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("royalty_percent");

                    b.HasKey("ProductId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenereId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProductIsbn")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("PublisherId");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.ProductAttribute", b =>
                {
                    b.Property<int>("ProdAttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prod_att_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProdAttId"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int")
                        .HasColumnName("attribute_id");

                    b.Property<string>("AttributeValue")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("attribute_value");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("ProdAttId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId", "AttributeId")
                        .IsUnique();

                    b.ToTable("product_attribute", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.ProductBeneficiary", b =>
                {
                    b.Property<int>("ProdbenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prodben_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProdbenId"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int")
                        .HasColumnName("beneficiary_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("RoyaltyReceived")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("royalty_received");

                    b.Property<int>("RoycalId")
                        .HasColumnType("int")
                        .HasColumnName("roycal_id");

                    b.HasKey("ProdbenId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RoycalId");

                    b.ToTable("product_beneficiary", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.ProductCover", b =>
                {
                    b.Property<int>("CoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cover_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CoverId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("LONGBLOB")
                        .HasColumnName("image_data");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("CoverId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("product_cover", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.ProductType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Type_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Type_Desc");

                    b.HasKey("TypeId");

                    b.HasIndex("TypeDesc")
                        .IsUnique();

                    b.ToTable("product_type_master", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Publisher_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("PublisherId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("publisher", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.ReadBook", b =>
                {
                    b.Property<int>("PdfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pdf_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PdfId"));

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<byte[]>("PdfData")
                        .HasColumnType("LONGBLOB")
                        .HasColumnName("pdf_data");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("PdfId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("pdf_book", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.RoyaltyCalculation", b =>
                {
                    b.Property<int>("RoycalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roycal_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoycalId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("RoyaltyPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("royalty_percent");

                    b.Property<DateOnly?>("RoycalTranDate")
                        .HasColumnType("date")
                        .HasColumnName("roycal_trandate");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("TotalRoyalty")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_royalty");

                    b.HasKey("RoycalId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("royalty_calculation", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("transaction_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.TransactionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.HasKey("ItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_items", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_Admin");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date")
                        .HasColumnName("Join_Date");

                    b.Property<string>("UserAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("User_Address");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("User_Email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("User_Name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("User_Password");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("User_Phone");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("BookwormApi.Models.BeneficiaryAssignment", b =>
                {
                    b.HasOne("BookwormApi.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_benassign_beneficiary");

                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_benassign_product");

                    b.Navigation("Beneficiary");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BookwormApi.Models.Cart", b =>
                {
                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_product");

                    b.HasOne("BookwormApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_user");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookwormApi.Models.LibraryPackagePurchase", b =>
                {
                    b.HasOne("BookwormApi.Models.LibraryPackage", "LibraryPackage")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_package");

                    b.HasOne("BookwormApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_transaction");

                    b.HasOne("BookwormApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_user");

                    b.Navigation("LibraryPackage");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookwormApi.Models.LibraryPackagePurchaseItem", b =>
                {
                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchitem_product");

                    b.HasOne("BookwormApi.Models.LibraryPackagePurchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchitem_purchase");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("BookwormApi.Models.MyLibrary", b =>
                {
                    b.HasOne("BookwormApi.Models.LibraryPackage", "LibraryPackage")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .HasConstraintName("fk_mylib_package");

                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_mylib_product");

                    b.HasOne("BookwormApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mylib_user");

                    b.Navigation("LibraryPackage");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookwormApi.Models.MyShelf", b =>
                {
                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shelf_product");

                    b.HasOne("BookwormApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shelf_user");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookwormApi.Models.Product", b =>
                {
                    b.HasOne("BookwormApi.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_product_author");

                    b.HasOne("BookwormApi.Models.Genere", "Genere")
                        .WithMany()
                        .HasForeignKey("GenereId")
                        .HasConstraintName("fk_product_genere");

                    b.HasOne("BookwormApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("fk_product_lang");

                    b.HasOne("BookwormApi.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("fk_product_type");

                    b.HasOne("BookwormApi.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("fk_product_publisher");

                    b.Navigation("Author");

                    b.Navigation("Genere");

                    b.Navigation("Language");

                    b.Navigation("ProductType");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookwormApi.Models.ProductAttribute", b =>
                {
                    b.HasOne("BookwormApi.Models.AttributeEntity", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodattr_attribute");

                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodattr_product");

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BookwormApi.Models.ProductBeneficiary", b =>
                {
                    b.HasOne("BookwormApi.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodben_beneficiary");

                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodben_product");

                    b.HasOne("BookwormApi.Models.RoyaltyCalculation", "RoyaltyCalculation")
                        .WithMany()
                        .HasForeignKey("RoycalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodben_roycal");

                    b.Navigation("Beneficiary");

                    b.Navigation("Product");

                    b.Navigation("RoyaltyCalculation");
                });

            modelBuilder.Entity("BookwormApi.Models.ProductCover", b =>
                {
                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cover_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BookwormApi.Models.ReadBook", b =>
                {
                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pdfbook_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BookwormApi.Models.RoyaltyCalculation", b =>
                {
                    b.HasOne("BookwormApi.Models.TransactionItem", "TransactionItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roycal_item");

                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roycal_product");

                    b.Navigation("Product");

                    b.Navigation("TransactionItem");
                });

            modelBuilder.Entity("BookwormApi.Models.Transaction", b =>
                {
                    b.HasOne("BookwormApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_transaction_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookwormApi.Models.TransactionItem", b =>
                {
                    b.HasOne("BookwormApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_txitem_product");

                    b.HasOne("BookwormApi.Models.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("fk_txitem_transaction");

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BookwormApi.Models.LibraryPackagePurchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BookwormApi.Models.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
